// Site data
    
        var siteData = [ 
                { name: "Paviland Cave", coordinates: [51.550144, -4.255517], age: "Paleolithic", type: "burial-hoard" },
                { name: "Kents Cavern", coordinates: [50.46772, -3.502676], age: "Paleolithic", type: "Cave-Early-Human-Occupation" },
                { name: "Gough's Cave", coordinates: [51.2819, -2.7654], age: "Paleolithic", type: "Cave-Early-Human-Occupation" },
                { name: "Creswell Crags", coordinates: [53.26347, -1.193535], age: "Paleolithic", type: "Cave-Early-Human-Occupation" },
                { name: "Eartham Pit", coordinates: [50.869542, -0.689675], age: "Paleolithic", type: "Cave-Early-Human-Occupation" },
                { name: "Swanscombe", coordinates: [51.444256, 0.296609], age: "Paleolithic", type: "Cave-Early-Human-Occupation" },
                { name: "Happisburgh", coordinates: [52.825278, 1.535], age: "Paleolithic", type: "Cave-Early-Human-Occupation" },
                { name: "Star Carr", coordinates: [54.214167, -0.423333], age: "Mesolithic", type: "Settlement" },
                { name: "Howick", coordinates: [55.454, -1.593], age: "Mesolithic", type: "Settlement" },
                { name: "Oare Marshes", coordinates: [51.344, 0.886], age: "Mesolithic", type: "Settlement" },
                { name: "Low Hauxley", coordinates: [55.3184, -1.5512], age: "Mesolithic", type: "Settlement" },
                { name: "Llyn Fawr", coordinates: [51.719722, -3.568333], age: "Mesolithic", type: "Settlement" },
                { name: "Mount Sandel", coordinates: [55.1161, -6.6642], age: "Mesolithic", type: "Settlement" },
                { name: "Skara Brae", coordinates: [59.048714, -3.34175], age: "Neolithic", type: "Settlement" },
                { name: "Pentre Ifan", coordinates: [51.999, -4.77], age: "Neolithic", type: "burial-hoard" },
                { name: "Bryn Celli Ddu", coordinates: [53.2077, -4.2361], age: "Neolithic", type: "burial-hoard" },
                { name: "Stonehenge", coordinates: [51.178889, -1.826111], age: "Neolithic", type: "ceremonial-religious" },
                { name: "Avebury", coordinates: [51.428611, -1.854167], age: "Neolithic", type: "ceremonial-religious" },
                { name: "Silbury Hill", coordinates: [51.4157, -1.8574], age: "Neolithic", type: "ceremonial-religious" },
                { name: "Callanish Stones", coordinates: [58.197541, -6.745145], age: "Neolithic", type: "ceremonial-religious" },
                { name: "Ring of Brodgar", coordinates: [59.001482, -3.229723], age: "Neolithic", type: "ceremonial-religious" },
                { name: "Must Farm", coordinates: [52.555236, -0.177319], age: "Bronze Age", type: "Settlement" },
                { name: "Grimspound", coordinates: [50.61331, -3.83738], age: "Bronze Age", type: "Settlement" },
                { name: "Flag Fen", coordinates: [52.574, -0.19], age: "Bronze Age", type: "ceremonial-religious" },
                { name: "Beaghmore", coordinates: [54.701466, -6.938701], age: "Bronze Age", type: "ceremonial-religious" },
                { name: "Milton Keynes Hoard", coordinates: [52.033, -0.711], age: "Bronze Age", type: "burial-hoard" },
                { name: "Rillaton Barrow", coordinates: [50.5211, -4.4557], age: "Bronze Age", type: "burial-hoard" },
                { name: "Glastonbury Lake Village", coordinates: [51.163611, -2.725833], age: "Iron Age", type: "Settlement" },
                { name: "Carn Euny", coordinates: [50.10234, -5.63448], age: "Iron Age", type: "Settlement" },
                { name: "Old Oswestry Hillfort", coordinates: [52.87273, -3.04886], age: "Iron Age", type: "castle-fort" },
                { name: "Maiden Castle", coordinates: [50.695, -2.47], age: "Iron Age", type: "castle-fort" },
                { name: "Danebury Hill Fort", coordinates: [51.136681, -1.537569], age: "Iron Age", type: "castle-fort" },
                { name: "Honington Camp", coordinates: [52.969925, -0.580756], age: "Iron Age", type: "castle-fort" },
                { name: "Llyn Cerrig Bach", coordinates: [53.25885, -4.540288], age: "Iron Age", type: "burial-hoard" },
                { name: "Roman Temple of Mithras", coordinates: [51.5125, -0.0906], age: "Roman", type: "ceremonial-religious" },
                { name: "Roman Baths", coordinates: [51.3809, -2.3595], age: "Roman", type: "ceremonial-religious" },
                { name: "Hoxne Hoard", coordinates: [52.3425, 1.1875], age: "Roman", type: "burial-hoard" },
                { name: "Colchester Roman Town", coordinates: [51.891944, 0.898056], age: "Roman", type: "Settlement" },
                { name: "Vindolanda", coordinates: [54.9911, -2.3608], age: "Roman", type: "castle-fort" },
                { name: "Housesteads Roman Fort", coordinates: [55.013, -2.331], age: "Roman", type: "castle-fort" },
                { name: "Bamburgh Castle", coordinates: [55.608, -1.709], age: "Anglo-Saxon", type: "castle-fort" },
                { name: "Lindisfarne Priory", coordinates: [55.68, -1.8025], age: "Anglo-Saxon", type: "ceremonial-religious" },
                { name: "Repton Abbey", coordinates: [52.841308, -1.55102], age: "Anglo-Saxon", type: "ceremonial-religious" },
                { name: "Bedale Hoard", coordinates: [54.29, -1.59], age: "Anglo-Saxon", type: "burial-hoard" },
                { name: "Prittlewell Princely Burial", coordinates: [51.55391, 0.70873], age: "Anglo-Saxon", type: "burial-hoard" },
                { name: "Sutton Hoo", coordinates: [52.089, 1.338], age: "Anglo-Saxon", type: "burial-hoard" },
                { name: "Spong Hill", coordinates: [52.737, 0.934], age: "Anglo-Saxon", type: "burial-hoard" },
                { name: "Canterbury Cathedral", coordinates: [51.2797, 1.0831], age: "Medieval", type: "ceremonial-religious" },
                { name: "Salisbury Cathedral", coordinates: [51.064722, -1.7975], age: "Medieval", type: "ceremonial-religious" },
                { name: "York Minster", coordinates: [53.961944, -1.081944], age: "Medieval", type: "ceremonial-religious" },
                { name: "Bodiam Castle", coordinates: [51.0023, 0.5435], age: "Medieval", type: "castle-fort" },
                { name: "Caernarfon Castle", coordinates: [53.1393, -4.2769], age: "Medieval", type: "castle-fort" }
            ];